# Generated by Django 5.1.2 on 2024-11-28 06:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internado_rotatorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioEvaluadoOfAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evaluate', models.TextField()),
                ('is_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=100)),
                ('ci_complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('ci_expedido', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_contacto', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('matricula_univ', models.CharField(max_length=50)),
                ('internado_rot', models.CharField(max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('is_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ult_actualizacion', models.DateTimeField(auto_now=True)),
                ('tiempo_est', models.TimeField()),
                ('is_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_estudio', to='estudiante.estudiante')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_estudio', to='internado_rotatorio.tema')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoCuestionarioTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.CharField(max_length=300)),
                ('is_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cuestionario_evaluado_of_ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_cuestionario_tema', to='estudiante.cuestionarioevaluadoofai')),
                ('progreso_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_cuestionario_tema', to='estudiante.progresoestudio')),
            ],
        ),
    ]
