# Generated by Django 5.1.2 on 2024-10-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidos',
        ),
    ]
