# Generated by Django 5.1.2 on 2024-11-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActividadCuestionario',
            new_name='ActividadCuestionarioTema',
        ),
    ]
