# Generated by Django 5.1.2 on 2024-10-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_estudiante_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='obervaciones',
            new_name='observaciones',
        ),
    ]
