# Generated by Django 5.1.2 on 2024-11-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_rename_actividadcuestionario_actividadcuestionariotema'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActividadCuestionarioTema',
            new_name='ResultCuestionarioEvaluadoTema',
        ),
    ]
