# Generated by Django 5.1.2 on 2024-10-13 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_remove_estudiante_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apellido_materno',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido_paterno',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
