# Generated by Django 5.1.2 on 2024-11-02 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_rename_actividadcuestionariotema_resultcuestionarioevaluadotema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCuestionarioTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.CharField(max_length=300)),
                ('is_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('progreso_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_cuestionario_tema', to='estudiante.progresoestudio')),
            ],
        ),
        migrations.CreateModel(
            name='CuestionarioEvaluadoOfAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evaluate', models.TextField()),
                ('is_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('result_cuestionario_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionario_evaluado_of_ai', to='estudiante.resultadocuestionariotema')),
            ],
        ),
        migrations.DeleteModel(
            name='ResultCuestionarioEvaluadoTema',
        ),
    ]
