# Generated by Django 5.1.2 on 2024-10-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_alter_estudiante_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
