# Generated by Django 5.1.2 on 2024-11-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_rename_result_cuestionario_estudiante_cuestionarioevaluadoofai_resultado_cuestionario_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionarioevaluadoofai',
            name='resultado_cuestionario_estudiante',
        ),
        migrations.AddField(
            model_name='resultadocuestionariotema',
            name='cuestionario_evaluado_of_ai',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resultado_cuestionario_tema', to='estudiante.cuestionarioevaluadoofai'),
            preserve_default=False,
        ),
    ]
