# Generated by Django 5.1.2 on 2024-10-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internado_rotatorio', '0004_rename_areainternadorotatorio_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='area',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
