# Generated by Django 5.1.2 on 2024-10-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internado_rotatorio', '0005_area_created_at_area_is_status_area_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='area_internado_rotatorio',
            new_name='area',
        ),
    ]
