# Generated by Django 5.1.2 on 2024-10-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internado_rotatorio', '0006_rename_area_internado_rotatorio_tema_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area',
            new_name='name',
        ),
    ]
