# Generated by Django 5.1.2 on 2024-10-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internado_rotatorio', '0007_rename_area_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='short_title',
            field=models.CharField(default='titulo', max_length=100),
            preserve_default=False,
        ),
    ]
