# Generated by Django 5.1.2 on 2024-10-11 09:08

import apps.usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('is_status', models.BooleanField(default=True)),
                ('user_type', models.CharField(choices=[('estudiante', 'Estudiante'), ('doctor', 'Doctor(a)'), ('administrativo', 'Administrativo')], max_length=50)),
                ('picture', models.ImageField(default='/media/usuario/profile.png', upload_to=apps.usuario.models.user_profile_directory_path, verbose_name='Picture')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
