# Generated by Django 5.1.2 on 2024-10-21 03:38

import apps.usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='picture',
            field=models.ImageField(blank=True, default='usuario/default_profile.png', null=True, upload_to=apps.usuario.models.user_profile_directory_path),
        ),
    ]
