# Generated by Django 5.1.2 on 2024-10-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_permiso_usuario_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='is_type_content',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='permiso',
            field=models.ManyToManyField(blank=True, related_name='usuario', to='usuario.permiso'),
        ),
    ]
