# Generated by Django 5.1.2 on 2024-10-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_permiso_is_type_content_alter_usuario_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='module',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
