# Generated by Django 5.1.2 on 2024-10-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_permiso_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='permiso',
            new_name='permisos',
        ),
    ]
