# Generated by Django 5.1.2 on 2024-11-01 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=100)),
                ('ci_complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('ci_expedido', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_contacto', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('grado_academico', models.CharField(max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('is_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_institucional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
