# Generated by Django 5.1.2 on 2024-10-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_institucional', '0002_personalinstitucional_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinstitucional',
            old_name='obervaciones',
            new_name='observaciones',
        ),
    ]
