# Generated by Django 5.1.2 on 2024-10-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_institucional', '0003_rename_obervaciones_personalinstitucional_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinstitucional',
            name='apellido_materno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinstitucional',
            name='apellido_paterno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinstitucional',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinstitucional',
            name='ci_expedido',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinstitucional',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinstitucional',
            name='grado_academico',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinstitucional',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinstitucional',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
